
package edu.asu.ows;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-08-23T13:26:58.477-07:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ExceptionReport", targetNamespace = "http://www.opengis.net/ows/1.1")
public class ServiceExceptionReport extends Exception {
    
    private net.opengis.ows._1.ExceptionReport exceptionReport;

    public ServiceExceptionReport() {
        super();
    }
    
    public ServiceExceptionReport(String message) {
        super(message);
    }
    
    public ServiceExceptionReport(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceExceptionReport(String message, net.opengis.ows._1.ExceptionReport exceptionReport) {
        super(message);
        this.exceptionReport = exceptionReport;
    }

    public ServiceExceptionReport(String message, net.opengis.ows._1.ExceptionReport exceptionReport, Throwable cause) {
        super(message, cause);
        this.exceptionReport = exceptionReport;
    }

    public net.opengis.ows._1.ExceptionReport getFaultInfo() {
        return this.exceptionReport;
    }
}
